trying S3 bucket

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -155,11 +155,12 @@ jobs:
         env:
           DIST_ID: ${{ env.CLOUDFRONT_DISTRIBUTION_ID }}
         run: |
-          set -euo pipefail
-          # Hashed assets rarely need invalidation; index.html usually enough.
-          aws cloudfront create-invalidation \
-            --distribution-id "$DIST_ID" \
-            --paths "/index.html" "/*"
+            echo "no cloudfront to invalidate yet..."
+        #   set -euo pipefail
+        #   # Hashed assets rarely need invalidation; index.html usually enough.
+        #   aws cloudfront create-invalidation \
+        #     --distribution-id "$DIST_ID" \
+        #     --paths "/index.html" "/*"
 
       # Only mark release after successful deploy
       - name: Push tag to origin
